name: ecommerece
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #packages
  http: ^1.1.2
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.6
  flutter_lints: ^3.0.1
  smooth_page_indicator: ^1.1.0  
  iconsax: ^0.0.8
  google_nav_bar: ^5.0.6
  # cupertino_icons: ^1.0.2

  #state managment
  get: ^4.6.5
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true


#assets
  assets:
    # - assets/images/
    - assets/icons/
    - assets/icons/brands
    - assets/icons/categories
    - assets/logos/
    - assets/images/
    - assets/images/on_board/
    - assets/images/animations/

#fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
